/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FPGA */

#ifndef _Included_FPGA
#define _Included_FPGA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FPGA
 * Method:    setMemory
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_FPGA_setMemory
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     FPGA
 * Method:    getMemory
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_FPGA_getMemory
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
